export { default as LandingPage } from './LandingPage'
export { default as Home  } from './Home'
export { default as DetailPage } from './DetailPage'
export { default as FormPage  } from './FormPage'
export { default as AboutPage } from './AboutPage'
export { default as NotFoundPage } from './NotFoundPage'
